#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open() as f:
        return list(csv.DictReader(f))


def score_row(row: dict[str, str], mode: str) -> tuple:
    result_rank = {"LOSS": 0, "DRAW": 1, "WIN": 2, "SKIP": 3}
    end_turn = int(row.get("end_turn") or 0)
    max_ms = max(int(row.get("max_left_ms") or 0), int(row.get("max_right_ms") or 0))

    if mode == "loss":
        return (0 if row["bot_result"] == "LOSS" else 1, -end_turn)
    if mode == "draw":
        return (0 if row["bot_result"] == "DRAW" else 1, -end_turn)
    if mode == "longest":
        return (-end_turn, result_rank.get(row["bot_result"], 9))
    if mode == "slowest":
        return (-max_ms, -end_turn)
    if mode == "fastest-win":
        return (0 if row["bot_result"] == "WIN" else 1, end_turn)
    if mode == "first":
        return (0,)
    raise ValueError(f"unknown mode: {mode}")


def choose_rows(rows: list[dict[str, str]], args: argparse.Namespace) -> list[dict[str, str]]:
    playable = [r for r in rows if r["bot_result"] != "SKIP" and r.get("log")]
    if args.seed is not None:
        playable = [r for r in playable if int(r["seed"]) == args.seed]
    if args.side:
        playable = [r for r in playable if r["bot_side"].lower() == args.side]
    playable = [r for r in playable if Path(r["log"]).exists()]
    playable.sort(key=lambda r: score_row(r, args.mode))
    return playable[:args.limit]


def copy_to_clipboard(text: str) -> bool:
    pbcopy = shutil.which("pbcopy")
    if not pbcopy:
        return False
    subprocess.run([pbcopy], input=text, text=True, check=True)
    return True


def print_row(row: dict[str, str], index: int) -> None:
    print(
        f"[{index}] seed={row['seed']} side={row['bot_side']} "
        f"result={row['bot_result']} reason={row['reason']} "
        f"turn={row['end_turn']} log={row['log']}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Pick and export logs for the NYPC web simulator.")
    parser.add_argument("csv", type=Path, help="results.csv generated by tools/evaluate.py")
    parser.add_argument("--mode", choices=["loss", "draw", "longest", "slowest", "fastest-win", "first"], default="longest")
    parser.add_argument("--seed", type=int)
    parser.add_argument("--side", choices=["left", "right"])
    parser.add_argument("--limit", type=int, default=1)
    parser.add_argument("--output", type=Path, help="Write selected log content to this file. Only valid with --limit 1.")
    parser.add_argument("--print-log", action="store_true", help="Print selected log content to stdout. Only valid with --limit 1.")
    parser.add_argument("--copy", action="store_true", help="Copy selected log content to clipboard with pbcopy when available.")
    args = parser.parse_args()

    if args.limit < 1:
        raise SystemExit("--limit must be positive")
    if args.limit != 1 and (args.output or args.print_log or args.copy):
        raise SystemExit("--output, --print-log, and --copy require --limit 1")

    rows = choose_rows(load_rows(args.csv), args)
    if not rows:
        raise SystemExit("No matching log found.")

    for i, row in enumerate(rows, 1):
        print_row(row, i)

    if args.limit != 1:
        return

    log_text = Path(rows[0]["log"]).read_text(errors="replace")
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(log_text)
        print(f"wrote={args.output}")
    if args.copy:
        if copy_to_clipboard(log_text):
            print("copied=clipboard")
        else:
            print("copied=no pbcopy found", file=sys.stderr)
    if args.print_log:
        print(log_text, end="")


if __name__ == "__main__":
    main()
